name: Docker Build, Test, and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build test image
      run: docker build -t backend-test ./backend
    
    - name: Run tests in Docker
      run: docker run --rm backend-test pytest
